use crate::domains::luna::{
    domain::Director,
    dto::{
        CreateDirectorDto, EntityCountDto, PaginatedResponse, PaginationQuery, SearchDirectorDto,
        UpdateDirectorDto,
    },
};
use async_trait::async_trait;
use sea_orm::{DatabaseConnection, DatabaseTransaction, DbErr};

#[async_trait]
/// Trait representing repository-level operations for director entities.
pub trait DirectorRepository: Send + Sync {
    /// Retrieves all directors from the database.
    async fn find_all(&self, db: &DatabaseConnection) -> Result<Vec<Director>, DbErr>;

    /// Finds a director by their unique identifier.
    async fn find_by_id(&self, db: &DatabaseConnection, id: i64)
        -> Result<Option<Director>, DbErr>;

    /// Finds director list by condition
    async fn find_list(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchDirectorDto,
    ) -> Result<Vec<Director>, DbErr>;

    /// Finds director list with pagination
    async fn find_list_paginated(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchDirectorDto,
        pagination: PaginationQuery,
    ) -> Result<PaginatedResponse<Director>, DbErr>;

    /// Creates a new director record within an active transaction.
    async fn create(
        &self,
        txn: &DatabaseTransaction,
        director: CreateDirectorDto,
    ) -> Result<(i64, bool), DbErr>;

    /// Updates an existing director record.
    async fn update(
        &self,
        txn: &DatabaseTransaction,
        id: i64,
        director: UpdateDirectorDto,
    ) -> Result<Option<Director>, DbErr>;

    /// Deletes a director by their unique identifier within an active transaction.
    async fn delete(&self, txn: &DatabaseTransaction, id: i64) -> Result<bool, DbErr>;

    /// Gets record counts grouped by directors.
    async fn get_director_record_counts(
        &self,
        db: &DatabaseConnection,
    ) -> Result<Vec<EntityCountDto>, DbErr>;
}

#[async_trait]
/// Repository trait for ordering the director list by a per-user affinity score.
///
/// Kept separate from [`DirectorRepository`] (which is generated by the shared
/// `impl_named_entity_repo!` macro) so the macro call stays untouched. The
/// score requires a per-user aggregate over the director's works
/// (`director` <- `record.director_id` -> `user_record_interaction`) that
/// cannot be expressed as a column `order_by`, so this method uses a custom
/// `PostgreSQL` query.
pub trait DirectorAffinityRepository: Send + Sync {
    /// Lists directors ordered by the current user's affinity score,
    /// descending, with `id` ascending as a stable tiebreak.
    ///
    /// The score combines two Bayesian-shrunk rates with a logarithmic
    /// absolute-volume factor over the director's works, where `total` is the
    /// distinct works, `viewed` is the distinct works the user viewed, and
    /// `liked` is the distinct works the user both liked and viewed (so
    /// `liked <= viewed <= total`):
    ///
    /// - shrunk viewed rate `(viewed + m_v*c_v) / (total + m_v)` and shrunk
    ///   liked rate `(liked + m_l*c_l) / (viewed + m_l)` pull small-sample
    ///   rates toward a prior, so a single viewed+liked work no longer scores
    ///   a perfect `1.0`;
    /// - a volume factor `1 + gamma*(ln(1+viewed) + beta*ln(1+liked))/ln(1+n0)`
    ///   lifts directors with many viewed/liked works, with diminishing returns.
    ///
    /// The score is a relative ordering key and is NOT bounded to `[0, 1]`; a
    /// director with `total = 0` scores `0` and sorts last. Hyper-parameters
    /// live as constants in the repository implementation.
    async fn find_list_paginated_by_affinity(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchDirectorDto,
        pagination: PaginationQuery,
        user_id: &str,
    ) -> Result<PaginatedResponse<Director>, DbErr>;
}
