use crate::domains::luna::{
    domain::Studio,
    dto::{
        CreateStudioDto, EntityCountDto, PaginatedResponse, PaginationQuery, SearchStudioDto,
        UpdateStudioDto,
    },
};
use async_trait::async_trait;
use sea_orm::{DatabaseConnection, DatabaseTransaction, DbErr};

#[async_trait]
/// Trait representing repository-level operations for studio entities.
pub trait StudioRepository: Send + Sync {
    /// Retrieves all studios from the database.
    async fn find_all(&self, db: &DatabaseConnection) -> Result<Vec<Studio>, DbErr>;

    /// Finds a studio by their unique identifier.
    async fn find_by_id(&self, db: &DatabaseConnection, id: i64) -> Result<Option<Studio>, DbErr>;

    /// Finds studio list by condition
    async fn find_list(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchStudioDto,
    ) -> Result<Vec<Studio>, DbErr>;

    /// Finds studio list with pagination
    async fn find_list_paginated(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchStudioDto,
        pagination: PaginationQuery,
    ) -> Result<PaginatedResponse<Studio>, DbErr>;

    /// Creates a new studio record within an active transaction.
    async fn create(
        &self,
        txn: &DatabaseTransaction,
        studio: CreateStudioDto,
    ) -> Result<(i64, bool), DbErr>;

    /// Updates an existing studio record.
    async fn update(
        &self,
        txn: &DatabaseTransaction,
        id: i64,
        studio: UpdateStudioDto,
    ) -> Result<Option<Studio>, DbErr>;

    /// Deletes a studio by their unique identifier within an active transaction.
    async fn delete(&self, txn: &DatabaseTransaction, id: i64) -> Result<bool, DbErr>;

    /// Gets record counts grouped by studios.
    async fn get_studio_record_counts(
        &self,
        db: &DatabaseConnection,
    ) -> Result<Vec<EntityCountDto>, DbErr>;
}

#[async_trait]
/// Repository trait for ordering the studio list by a per-user affinity score.
///
/// Kept separate from [`StudioRepository`] (which is generated by the shared
/// `impl_named_entity_repo!` macro) so the macro call stays untouched. The
/// score requires a per-user aggregate over the studio's works
/// (`studio` <- `record.studio_id` -> `user_record_interaction`) that cannot be
/// expressed as a column `order_by`, so this method uses a custom `PostgreSQL`
/// query.
pub trait StudioAffinityRepository: Send + Sync {
    /// Lists studios ordered by the current user's affinity score, descending,
    /// with `id` ascending as a stable tiebreak.
    ///
    /// The score combines two Bayesian-shrunk rates with a logarithmic
    /// absolute-volume factor over the studio's works, where `total` is the
    /// distinct works, `viewed` is the distinct works the user viewed, and
    /// `liked` is the distinct works the user both liked and viewed (so
    /// `liked <= viewed <= total`):
    ///
    /// - shrunk viewed rate `(viewed + m_v*c_v) / (total + m_v)` and shrunk
    ///   liked rate `(liked + m_l*c_l) / (viewed + m_l)` pull small-sample
    ///   rates toward a prior, so a single viewed+liked work no longer scores
    ///   a perfect `1.0`;
    /// - a volume factor `1 + gamma*(ln(1+viewed) + beta*ln(1+liked))/ln(1+n0)`
    ///   lifts studios with many viewed/liked works, with diminishing returns.
    ///
    /// The score is a relative ordering key and is NOT bounded to `[0, 1]`; a
    /// studio with `total = 0` scores `0` and sorts last. Hyper-parameters live
    /// as constants in the repository implementation.
    async fn find_list_paginated_by_affinity(
        &self,
        db: &DatabaseConnection,
        search_dto: SearchStudioDto,
        pagination: PaginationQuery,
        user_id: &str,
    ) -> Result<PaginatedResponse<Studio>, DbErr>;
}
